version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - photo_data:/app/photos
  telegram-bot:
    build:
      context: .
      dockerfile: dockerfile.bot
    volumes:
      - .:/app
      - photo_data:/app/photos
    depends_on:
      - flask-app

volumes:
  photo_data: